<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class StudentCard extends Model
{
    protected $fillable = [
        'agency_id',

        'no1',
        'name1',
        'kelas1',
        'alamat1',
        'darah1',
        'agama1',
        'kelamin1',
        'nis1',
        'nisn1',
        'ttl1',
        'write_at1',

        'no2',
        'name2',
        'kelas2',
        'alamat2',
        'darah2',
        'agama2',
        'kelamin2',
        'nis2',
        'nisn2',
        'ttl2',
        'write_at2',

        'no3',
        'name3',
        'kelas3',
        'alamat3',
        'darah3',
        'agama3',
        'kelamin3',
        'nis3',
        'nisn3',
        'ttl3',
        'write_at3',

        'no4',
        'name4',
        'kelas4',
        'alamat4',
        'darah4',
        'agama4',
        'kelamin4',
        'nis4',
        'nisn4',
        'ttl4',
        'write_at4',

        'no5',
        'name5',
        'kelas5',
        'alamat5',
        'darah5',
        'agama5',
        'kelamin5',
        'nis5',
        'nisn5',
        'ttl5',
        'write_at5',

        'no6',
        'name6',
        'kelas6',
        'alamat6',
        'darah6',
        'agama6',
        'kelamin6',
        'nis6',
        'nisn6',
        'ttl6',
        'write_at6',

        'no7',
        'name7',
        'kelas7',
        'alamat7',
        'darah7',
        'agama7',
        'kelamin7',
        'nis7',
        'nisn7',
        'ttl7',
        'write_at7',

        'no8',
        'name8',
        'kelas8',
        'alamat8',
        'darah8',
        'agama8',
        'kelamin8',
        'nis8',
        'nisn8',
        'ttl8',
        'write_at8',

        'no9',
        'name9',
        'kelas9',
        'alamat9',
        'darah9',
        'agama9',
        'kelamin9',
        'nis9',
        'nisn9',
        'ttl9',
        'write_at9',

        'no10',
        'name10',
        'kelas10',
        'alamat10',
        'darah10',
        'agama10',
        'kelamin10',
        'nis10',
        'nisn10',
        'ttl10',
        'write_at10',
    ];
}
